name: gammapy-0.18.2

channels:
  - conda-forge
  - sherpa

dependencies:
  - gammapy=0.18.2
  - python=3.8
  - ipython
  - jupyter
  - jupyterlab=3
  - pyyaml
  - click
  - numpy
  - scipy
  - pandas
  - matplotlib=3
  - astropy=4.2
  - regions=0.4
  - iminuit=1
  - sherpa=4
  - healpy=1
  - naima=0.9
  - pydantic=1
  - emcee=2
  - corner=2.0
  - parfive=1
  - pip
  - requests
